language: python
python:
  - "3.6"
  

install:
  - pip install pipenv
  - pipenv install

# command to run tests
script:
  - python3 -m pytest --cov-report term --cov=app 

after_success:
  - coveralls