language: python
python:
  - "3.6"
  

install:
  - pip install pipenv
  - pipenv install

# command to run tests
script:
  - python3 -m pytest --cov-report term --cov=app 
  
before_script:
  - psql -c 'create database testdb;' -U postgres

services:
  - postgresql
  - memcached

addons:
  postgresql: "9.4"

after_success:
  - coveralls